### ISSUE TITLE
removing references to Dart Editor and build.dart

### ISSUE THREAD

**Issue by sethladd** [a14n/build_system.dart#7]
Hi!

Thanks for working on this package. It looks very useful for some internal projects we have.

However, some of our internal customers were scared off by all the references to Dart Editor and build.dart. Those references probably made sense a while ago, but today are just confusing.

What do you think about changing the description of the project to focus more on what it does and why it's useful, and assume the reader doesn't know about DE or build.dart ?

(you could keep those references at the bottom of a README, if you like)

I think making this project appear useful on its own (outside the context of Dart Editor) would help.

Thanks!

**Comment by a14n** [comment]
Fixed by #8

**Comment by a14n** [comment]
Published in _0.0.3+1_
